### ISSUE TITLE
Is this Project still in developmode?

### ISSUE THREAD

**Issue by denis-adobe** [comina/Socket#1]
If i compile it with Visual Studio 2013 i have errors like:
 unsigned int Socket::_num_sockets = 0; in CommonSocket.cpp:33  could not be found
when i fixed it to a normal unsigned int (because you try to set but it is in private) it compiled until that error:

Error   1   error C2664: 'int send(SOCKET,const char *,int,int)' : cannot convert argument 2 from 'const unsigned __int64 *' to 'const char *'  c:\users...\documents\visual studio 2013\projects\private\socket\tcp.cpp   114 1   Socket

I would appreciate if i can support this project. But maybe it works just fine and I just dont get what I am doing wrong.

**Comment by comina** [comment]
The errors you pointed out should be fixed now.
I don't have a quick way to test it under Windows so if there are any more problems you are more than welcome to "pull request" fixes for them.

It's not under development anymore, I guess, it'is an old high-school project so it surely needs lots of cleanups :)
